.type Word

// Read in all the bigrams and seven grams
.decl bigram (w:Word, w1:Word) input
.decl sevengram (w:Word, w1:Word, w2:Word, w3:Word, w4:Word, w5:Word, w6:Word) input

// Each "sentence" is 7 words long
.decl sentence (a:Word, b:Word, c:Word, d:Word, e:Word, f:Word, g:Word) output

sentence(a, b, c, d, e, f, g) :- bigram(a, b), bigram(b, c),
	bigram(c, d), bigram(d, e), bigram(e, f), bigram(f, g),
	a!= c, c != e, e != g, b != d, d != f,
	!sevengram(a, b, c, d, e, f, g).
